
// Objective-C API for talking to the following Go packages
//
//	lovehan1me/echgate/gate
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Echgate_FRAMEWORK_H__
#define __Echgate_FRAMEWORK_H__

#include "Gate.objc.h"
#include "Universe.objc.h"

#endif
