// Objective-C API for talking to lovehan1me/echgate/gate Go package.
//   gobind -lang=objc lovehan1me/echgate/gate
//
// File is generated by gobind. Do not edit.

#ifndef __Gate_H__
#define __Gate_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GateConfig;
@class GateServer;

/**
 * Config 是网关的全部输入（CLI flag 与 gomobile 调用共用同一形状，
只用 string/int64 切片与时长毫秒——保持 gomobile 可绑定）。
 */
@interface GateConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull listenAddr;
// skipped field Config.CfIPs with unsupported type: []string

// skipped field Config.CfHosts with unsupported type: []string

@property (nonatomic) NSString* _Nonnull dohURL;
@property (nonatomic) NSString* _Nonnull echDomain;
@property (nonatomic) NSString* _Nonnull echB64;
@property (nonatomic) NSString* _Nonnull cacheDir;
/**
 * TimeoutMs 上游连接超时毫秒（<=0 则用默认值）。
 */
@property (nonatomic) int64_t timeoutMs;
@end

/**
 * Server 是运行中的网关。Close 后端口释放，复用方（桌面进程管理 / gomobile）
据此做开关。
 */
@interface GateServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Addr 返回实际监听地址（`127.0.0.1:0` 由内核分配时，调用方靠它知道端口）。
 */
- (NSString* _Nonnull)addr;
/**
 * Close 停止网关。
 */
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
@end

// skipped function SplitList with unsupported parameter or return types


// skipped function Start with unsupported parameter or return types


/**
 * gomobile 绑定 facade。

gobind 不支持 struct 参数与 []string 字段（Config 会被整个跳过），
故这里提供扁平签名的入口：列表走逗号分隔字符串（与 CLI flag 同形状），
返回 (*Server, error)（对象 + 错误是支持的）。
CLI (`main.go`) 与 gomobile (Android `.aar` / iOS framework) 共用 [Start]。
 */
FOUNDATION_EXPORT GateServer* _Nullable GateStartFlat(NSString* _Nullable listenAddr, NSString* _Nullable cfIPsCSV, NSString* _Nullable cfHostsCSV, NSString* _Nullable dohURL, NSString* _Nullable echDomain, NSString* _Nullable echB64, NSString* _Nullable cacheDir, int64_t timeoutMs, NSError* _Nullable* _Nullable error);

#endif
